### ISSUE TITLE
--substr outputs too many sequences

### ISSUE THREAD

**Issue by nterhoeven** [BioInf-Wuerzburg/SeqFilter#2]
When running SeqFilter with the --substr option, sequences that are not represented in the substring-file show up completely in the output. I would expect them to not be present at all.

Example:
```
$ cat test.fa
>1
AGTCTGCTCGCTCGATCGACTACGATCCGATCGCTAGCTACGTACGAGCTACGAGCTCGATCGGACTG
>2
CGATCGACTACGACGATCGAGCATCAGAGCTCGCTCGCTCGCTCGGCTGATCGAAAGCAG
>3
ACTGCCGACTACTGCATAACCCATCGGCATTACGCGATTCGATACGACTGACGATCTAGTCACG

$ cat substr.tab
1	3	7
1	2	42
2	25	12
```
Running 

```
SeqFilter --substr substr.tab --out test.out test.fa
```

Result:
```
$ cat test.out 
>1.1 SUBSTR:3,5
CTGCT
>1.2 SUBSTR:2,41
TCTGCTCGCTCGATCGACTACGATCCGATCGCTAGCTACGT
>2 SUBSTR:12,14
TGATGCTCGATCGT
>3
ACTGCCGACTACTGCATAACCCATCGGCATTACGCGATTCGATACGACTGACGATCTAGTCACG
```
Expected Result:
```
$ cat test.out 
>1.1 SUBSTR:3,5
CTGCT
>1.2 SUBSTR:2,41
TCTGCTCGCTCGATCGACTACGATCCGATCGCTAGCTACGT
>2 SUBSTR:12,14
TGATGCTCGATCGT
```

**Comment by thackl** [comment]
You are right about that, but it is kind of intended, although not entirely intuitive, I guess. The main reason for this behaviour is, that it is very easy to achieve what you want to do: modify and filter sequences at the same time, just add `--ids substr.tab` to the command:

```
# modify set of sequences and only output modified sequences:
SeqFilter --substr substr.tab --ids substr.tab --out test.out test.fa
```

In contrast, it would require quite large substr files (including all ids) if one only wants to modify a few sequences from a large file and still keep everything.

**Comment by nterhoeven** [comment]
Ah I see. Didn't know, that `--ids substr.tab` could be used like this :-)
